import { SearchQuery } from "@/components/search-query";
import { QueryProvider } from "@/providers/query.provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gerenciado de Boletos",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children, ...props
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>

          {children}
          <Suspense fallback={<div />}>
            <SearchQuery />

          </Suspense>
        </QueryProvider>
      </body>
    </html>
  );
}
